### ISSUE TITLE
Executing and closing wallpaper a second time causes "pointer trails" etc.

### ISSUE THREAD

**Issue by Kazinsal** [klange/toaruos#103]
![wallpaper](https://cloud.githubusercontent.com/assets/531253/8640706/579808b0-28b6-11e5-9ed5-f99b69bb6761.png)

Steps to reproduce:
1. Execute `wallpaper`.
2. `kill` or otherwise terminate the new `wallpaper` process.
3. Move the mouse over the existing wallpaper, close or move a window, etc.

**Comment by klange** [comment]
Ah, here's the explanation for this one:
- The wallpaper window occupies a special z-index slot for the "bottom" window. Other windows that occupy this slot include the login screen when applicable. There is another "top" window slot for the panel. Only one window can be in each of these slots at the moment.
- When you launch a new wallpaper, it pushes the old wallpaper out of the bottom slot and replaces it.
- When you close the wallpaper, you end up with no window in the bottom slot.
- The compositor doesn't clear the screen during redraws, as /normally/ there will be a full-screen, opaque bottom window (login, wallpaper), but now you don't have one, so you get ghosting.

The correct solution to this is to finish implementing the multiple bottom/top slots, so that launching a new wallpaper instance doesn't clobber the old one. A workaround would be to keep track of windows that were in the bottom slot and put one back if it becomes empty. Another possibility is to do a bit more work to prevent the wallpaper from being run again (along with the panel, and various other conflicting applications, like `terminal-vga` or other instances of the compositor).

**Comment by klange** [comment]
The wallpaper app responds to `SIGUSR2` to reclaim its hold on the bottom layer slot, which should be a sufficient workaround for this... maybe...
