### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Shashwat-AI** [klange/toaruos#124]
hi kevin,

when i compile toaruOS or ponyOS i get this error

Makefile:1089: recipe for target 'cp/except.o' failed
make[2]: *** [cp/except.o] Error 1
make[2]: Leaving directory '/home/shashwat/Downloads/ponyos-master/toolchain/build/gcc/gcc'
Makefile:5265: recipe for target 'all-gcc' failed
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory '/home/shashwat/Downloads/ponyos-master/toolchain/build/gcc'
Build failed. Please check the logs above to see what went wrong.

i'm using ubuntu 15.10

plz..help!

P.S sorry for my bad english

Best Regards,
shashwat

**Comment by klange** [comment]
You need to provide significantly more of the error log than that, as you are missing the part that actually says what the problem is.

**Comment by EggProphet** [comment]
Ah, I came across this myself. From the information I could find this is due to an error in gcc 5.x versions that causes incompatibility during compiling with the 4.6.4 version of gcc included with the toolchain. Seeing as you're on Ubuntu this should fix your problem:

This will uninstall you current version of gcc and g++ and install 4.6, fixing the incompatibility error you're experiencing in the process.

sudo apt-get remove gcc g++
Add these two lines in /etc/apt/sources.list (To gain access other gcc and g++ versions):
deb http://archive.ubuntu.com/ubuntu/ trusty universe  
deb-src http://archive.ubuntu.com/ubuntu/ trusty universe
sudo apt-get install gcc-4.6 g++-4.6

Then try recompiling the kernel. (You should start with a fresh toolchain, so delete the "build" "local" and "tarballs" directories in the toolchain directory before proceeding with the compile.)

**Comment by klange** [comment]
Installing packages from older versions of Ubuntu is terrible advice. The correct fix for the gcc incompatibility is in #110 - patching the gcc 4.6 sources to build correctly. We had a pull request to add this patch, but it was retracted. As I do not actively maintain ToaruOS anymore, I have yet to add the patch myself, and only recently upgraded away from an older LTS release of Ubuntu myself.

**Comment by gerow** [comment]
You might consider adding a new upstream maintainer, for those still enthusiastic about development for toaruos. Or at least naming a 'blessed' upstream fork.

**Comment by griwes** [comment]
@klange how dare you back up from maintaining this?!

:P
