### ISSUE TITLE
Username box does not scroll or truncate text

### ISSUE THREAD

**Issue by matt11235** [klange/toaruos#143]
Not particularly important, but text entered into the username and password boxes can overrun and spoil the background beneath.

![](http://i.imgur.com/bzM5quu.png)

**Comment by matt11235** [comment]
I'm not sure if this should be a part of #63 or not.

**Comment by shevegen** [comment]
I guess it can stay independent of #63. And I also think that this may be applicable to other widget-behaviour where text-input is used, so I assume that this may be fixed.

Not sure what fix would be appropriate since I assume there could be several ways for this; one may be to make the input-widget bigger when the threshold value exceeds, onto the next line. Another simple one may be to simply "assume" that the line may be longer, but to only show the last n characters, so that when a user continues to type, the input-focus will be more to the right hand side of the input, e. g. the whole text can be horizontally scrolled, but you only see that input widget size. (On a side note, perhaps the input field should be a tiny bit larger, but I am not sure if this is wanted or needed.)

**Comment by klange** [comment]
I've been working on a more complete implementation of a text input box which should at least support clipping (it also supports arbitrary editing and cursor positioning), but it's part of the Python UI toolkit and the graphical login remains a "legacy" C application that hasn't gotten much love since it's not part of the main live CD experience.

**Comment by klange** [comment]
I'm working on a new login manager in Python, so that it can make use of the widget toolkit, which should resolve this issue eventually as the widget toolkit's text input boxes (as mentioned previously) actually clip their contents. I'm also changing up the design of the login manager a bit: adding a panel (same as the desktop, but with some changes to the widgets), possibly changing the input boxes, etc. With this new Python login manager, I want to change how the login system works a bit. At the moment, the graphical login app stays running in the background waiting for you to log out so it can show itself again, but it eats up gobs of memory it can't easily free, so it would be better to hide it and relaunch it after logout, so the plan at the moment is to keep a light-weight app in the background to manage the login manager.
