### ISSUE TITLE
Touchpad too slow!

### ISSUE THREAD

**Issue by ghost** [klange/toaruos#152]
Hi !
I just tried your live ISO on my HP laptop and (for me) the touchpad speed is too slow !
You should increase the touchpad speed.

Thanks.

**Comment by klange** [comment]
A video or other demonstration of the mouse speed would be appreciated, given the speed is perfectly reasonable in all of the environments I have tested in (including a laptop with a touchpad).

**Comment by cr6void** [comment]
Thanks for your quick response, I'm glad to see you are **OP** even the Sunday :+1: )

My laptop is an HP dv6, [this model](http://support.hp.com/us-en/product/HP-Pavilion-dv6-Entertainment-Notebook-PC-series/4041735/model/4116094/) to be precise...

Yes there are many different dv6 models, but it's **not uncommon** hardware at all.

At least I hope I helped you a bit with **this** report, even if your are not open to **discuss** RAM usage with me, no problem, I can understand.

**I really hope** you will continue to improve your OS, because it's an **encouraging beginning** !

**Comment by klange** [comment]
I should probably add a configuration option for the mouse speed and acceleration. The trouble is that things are currently configured for one mouse unit = one pixel, so things can't just be sped up or you wouldn't be able to accurately position the mouse. We have no acceleration at the moment, so that's an option that may help. Something I want to work on for an upcoming release is a full settings panel with lots of configuration options for the things I've previously left at what I had hoped were "reasonable defaults".

**Comment by cr6void** [comment]
No acceleration at the moment ? OK I understand.

A full settings panel with lots of config options ? Why not, but please **KEEP IT SIMPLE.**

In my view the _perfect_ settings panel should be _didactic_ with the user.

I mean: when I click to enable or disable some options I would like to **see** which config files are actually modified and how they are modied.
I mean: when I change my touchpad settings (for example), I would like to **see** which settings are modified in which config files...

I hope you see what I mean.

But I **never** see such functionality in any settings panel... They remain silent when they change something in the system, and it **does not help the beginner** to understand the internal system organization.
