### ISSUE TITLE
Community?

### ISSUE THREAD

**Issue by turbocat2001** [klange/toaruos#229]
Such an interesting OS will gather many fans.  Why not create channels on Telegram or Discord?  Using IRC in 2022 is not loving your fans...

**Comment by klange** [comment]
I have an IRC channel because ToaruOS has an IRC client. It is highly unlikely ToaruOS will ever have a Discord or Telegram client (or be able to use either of those services through web clients), so there is no reason to run communities on those platforms.

There is an accessible forum already set up through [Github Discussions](https://github.com/klange/toaruos/discussions), which is where you should have posted this question. Issue reports are for technical problems with the OS.

**Comment by BlackPhrase** [comment]
>It is highly unlikely ToaruOS will ever have a Discord or Telegram client (or be able to use either of those services through web clients)

Nothing is impossible
