### ISSUE TITLE
Can't build gcc toolchain

### ISSUE THREAD

**Issue by turbocat2001** [klange/toaruos#231]
Maybe I'm doing something wrong, but when I run ./build-toolchain.sh , the build fails with the error: 
"g++: error: gengtype-lex.c: No such file or directory g++: fatal error: no input files" 

My gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1).
Tried both Ubuntu 21.04 and Cygwin with the same result.

PS. I would be glad to find an already builded version for windows or linux

**Comment by klange** [comment]
There is an "already built" toolchain in the form of a Docker container, which also contains some of the other tools necessary for the build: https://github.com/klange/toaruos#building-with-docker - Since building a whole OS is a complicated task, I generally suggest not trying to build the toolchain or perform builds directly, and can't feasibly support trying to do it outside of an environment that matches my own Ubuntu host system (and I'm still on the LTS); using the Docker container avoids a number of issues, including the fact that it can take up to an hour to build the gcc cross-compiler.

All that said, from a quick perusal of the GCC sources, I believe that file is built with `flex` from a `.l` source, which might suggest you are missing `flex` (you might be able to confirm this with earlier error messages). Check that you have all of the required packages, most of which are just for building gcc, as listed in the Dockerfile used to build the CI images: https://github.com/klange/toaruos/blob/master/util/docker/Dockerfile#L6

**Comment by turbocat2001** [comment]
Can I use gcc from linux with a linker script as a temporary solution?

**Comment by klange** [comment]
No. A fully targeted cross-compiler is required to build the userspace.

**Comment by turbocat2001** [comment]
Building via docker really helped
