### ISSUE TITLE
Compromised user passwords.

### ISSUE THREAD

**Issue by Doczom** [klange/toaruos#252]
From turbocat2001:

> With "strace sudo" all user passwords can be compromised. To do this, you need to patch strace by increasing the output for the "read" syscall.

**Comment by klange** [comment]
This misses the actual issue which is that a ptrace'd process that execs a SUID binary should not actually SUID.

**Comment by klange** [comment]
There are many situations the SUID handling doesn't catch that it should - ToaruOS is not secure and the entire infrastructure behind `sudo` is a toy, a facsimile of the real deal.

Anyway, fixed in 5f643d703478a5f36a1c00ef1171d1b0429537c5 and `sudo` will report when it didn't get an effective uid of 0 as of 2391009167255fe2b289a72508ee532927ea0ca8

**Comment by klange** [comment]
@turbocat2001 You're unblocked, file your own bug reports.
